name: publish to nuget
on:
  push:
    branches:
      - main # Default release branch
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.x
          
      - name: Install dependencies
        run: dotnet restore
        
      - name: Build
        run: dotnet build --configuration Release --no-restore
      
      #- name: Test
      #  run: dotnet test --no-restore --verbosity normal
      
      - name: Pack MakeSimple.SharedKernel project
        run: dotnet pack src/MakeSimple.SharedKernel/MakeSimple.SharedKernel.csproj --no-build --configuration Release --include-symbols -p:SymbolPackageFormat=snupkg -o .
    
      #- name: publish package to GitHub
      #  run: dotnet nuget push *.nupkg --api-key ${{secrets.PUBLISH_TO_GITHUB_TOKEN}} --source "https://nuget.pkg.github.com/VAllens/index.json" --skip-duplicate
      
      - name: Pack MakeSimple.SharedKernel.Infrastructure project
        run: dotnet pack src/MakeSimple.SharedKernel.Infrastructure/MakeSimple.SharedKernel.Infrastructure.csproj --no-build --configuration Release --include-symbols -p:SymbolPackageFormat=snupkg -o .
      
      #- name: publish package to GitHub
      #  run: dotnet nuget push *.nupkg --api-key ${{secrets.PUBLISH_TO_GITHUB_TOKEN}} --source "https://nuget.pkg.github.com/VAllens/index.json" --skip-duplicate
      
      - name: Pack MakeSimple.SharedKernel.Extensions project
        run: dotnet pack src/MakeSimple.SharedKernel.Extensions/MakeSimple.SharedKernel.Extensions.csproj --no-build --configuration Release --include-symbols -p:SymbolPackageFormat=snupkg -o .
      
      - name: Publish all package to NuGet
        id: publish_nuget_makesimple_sharedkernel
        run: dotnet nuget push /home/runner/work/MakeSimple.SharedKernel/MakeSimple.SharedKernel/*.nupkg --api-key ${{secrets.NUGET_API_KEY}} --source "https://api.nuget.org/v3/index.json" --skip-duplicate
      
      #- name: publish package to GitHub
      #  run: dotnet nuget push *.nupkg --api-key ${{secrets.PUBLISH_TO_GITHUB_TOKEN}} --source "https://nuget.pkg.github.com/VAllens/index.json" --skip-duplicate
